Dev
sfcsumb/CST438-Gradebook-backend-forgacs pull request #6
Opened 2023-07-18 20:30 UTC by sfcsumb

Fixed missing query in AssignmentRepository.java for testing and renamed function to clarify it is to find an assignment.

2023-07-19 01:31 UTC, denizozgur commented on cst438_gradebook/src/main/java/com/cst438/domain/AssignmentRepository.java
> +	List<Assignment> findAssignmentByCourseIdAndName(int id, String name);
```suggestion

	@Query("select a from Assignment a where a.course.course_id= :id and a.name= :name")
	List<Assignment> findAssignmentByCourseIdAndName(@Param("id") int id,@Param("name") String name);
```

2023-07-19 01:32 UTC, denizozgur commented on cst438_gradebook/src/test/java/com/cst438/EndToEndTestAssignments.java
> +			Optional<Assignment> a = assignmentRepository.findAssignmentByCourseIdAndName(TEST_COURSE_ID, TEST_ASSIGNMENT_NAME);
Doesn't return Optional<Assignment> anymore 

```suggestion
			List<Assignment> a = assignmentRepository.findAssignmentByCourseIdAndName(Integer.parseInt(TEST_COURSE_ID), TEST_ASSIGNMENT_NAME);
```

2023-07-19 01:34 UTC, denizozgur commented on cst438_gradebook/src/test/java/com/cst438/EndToEndTestAssignments.java
>  				assignmentRepository.delete(a);
delete requires a single entity below will be the first item of the list if it's populated
```suggestion
				assignmentRepository.delete(a.get(0));
```

2023-07-19 01:34 UTC, denizozgur commented on cst438_gradebook/src/test/java/com/cst438/EndToEndTestAssignments.java
>  				assignmentRepository.delete(a);
same problem as line 83

2023-07-19 01:37 UTC, denizozgur requested changes
I can't compile the code without these changes

2023-07-20 00:28 UTC, sfcsumb commented on cst438_gradebook/src/main/java/com/cst438/domain/AssignmentRepository.java
> +	List<Assignment> findAssignmentByCourseIdAndName(int id, String name);
Sorry, you are correct.

2023-07-20 00:31 UTC, sfcsumb commented on cst438_gradebook/src/test/java/com/cst438/EndToEndTestAssignments.java
>  				assignmentRepository.delete(a);
Fixed

2023-07-23 20:03 UTC, denizozgur approved these changes

2023-07-23 20:03 UTC, merged